name: Feature Request
description: Request a Feature
body:
  - type: markdown
    attributes:
      value: |
        Use this form to request a new Feature or an update to an existing Feature in Foundry
  - type: textarea
    id: user-experience
    attributes:
      label: User Experience
      description: What problem does this solve? What should it function like?
      placeholder: In order to help with bulk creation of documents, I would like a new button...
      value: "Please add a bulk creation workflow"
    validations:
      required: true
