name: Add V10 milestoned Issues to V10 Project

on:
  issues:
    types: [milestoned]

jobs:
  add-to-project:
    name: Add Issue to V10 Maintenance
    runs-on: ubuntu-latest
    steps:
      - uses: cswendrowski/add-to-project@v2.2.0
        with:
          project-url: https://github.com/orgs/foundryvtt/projects/30
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          milestoned: Version 10
          remove-unmatched: false
          fuzzy-match: true
